group = 'com.uniquelab.donttouchmyphone.guard'
version = '0.1.0'

apply plugin: 'com.android.library'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()

android {
  namespace 'com.uniquelab.donttouchmyphone.guard'
  defaultConfig { minSdkVersion 23 }
}

dependencies {
  implementation 'androidx.core:core-ktx:1.13.1'
}
